// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config() {
  return window['go']['app']['App']['Config']();
}

export function LogFilePath() {
  return window['go']['app']['App']['LogFilePath']();
}

export function Ping(arg1) {
  return window['go']['app']['App']['Ping'](arg1);
}

export function PingVersion() {
  return window['go']['app']['App']['PingVersion']();
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}
