// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Config():Promise<config.Config>;

export function LogFilePath():Promise<string>;

export function Ping(arg1:string):Promise<string>;

export function PingVersion():Promise<number>;

export function SetTheme(arg1:string):Promise<void>;
